- project:
    name: ^.*$
    gate:
      jobs: []
    checklabel_emea:
      jobs: []
    checklabel_nafta:
      jobs: []
    check_emea:
      jobs: []
    check_nafta:
      jobs: []
#    pullrequest_label:
#      jobs: []
    merge:
      jobs: []
