- project:
    name: ^.*$
    check:
      jobs: []
    gate:
      jobs: []
    region1:
      jobs: []
    region2:
      jobs: []
    pullrequest_label:
      jobs: []
    pullrequest_dependent:
      jobs: []
