- project:
    name: ^.*$
    gate:
      jobs: []
    checklabel_emea:
      jobs: []
    checklabel_nafta:
      jobs: []
    check_emea:
      jobs: []
    check_nafta:
      jobs: []

- project:
    name: fca-project
    pullrequest_label:
      jobs: []
