- project:
    name: ^.*$
    checklabel_emea:
      jobs: []
    checklabel_nafta:
      jobs: []
    check_emea:
      jobs: []
    check_nafta:
      jobs: []
    periodic:
      jobs: []
    gate:
      jobs: []

- project:
    name: zuul-hcl-org/zuul-config
    check:
      jobs:
        - noop
    gate:
      jobs:
        - noop
